---
title: "Week 6: Strings, Factors, and Datetimes"
author: "Ryan Harrington"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
library(lubridate)

theme_set(theme_minimal())
```

```{r}
foia <- read_excel(here::here("Data", "OMB FOIA TRACKING 032719.xlsx"))
```

```{r}
glimpse(foia)
```

```{r}
foia <- janitor::clean_names(foia)

glimpse(foia)
```

```{r}
foia <-
  foia %>% 
  rename("date_received" = date_written_request_received_by_agency,
         "date_assigned" = assigned_date,
         "division" = omb_division,
         "date_review" = agency_review_date,
         "is_noncustodial_record" = does_the_request_seek_non_custodial_records_from_dti_omb_or_any,
         "noncustodial_provided_other_agency" = if_non_custodial_records_were_provided_by_another_agency_provid,
         "date_response" = date_of_agency_response_to_requesting_party_under_34_of_policy,
         "date_estimate_sent" = estimate_sent,
         "all_requested_records_sent" = were_all_requested_records_provided_on_date_of_agency_s_respons,
         "date_requested_records_not_provided" = if_all_requested_records_were_not_provided_as_of_date_of_agency,
         "copying_fees" = copying_fees_note_1st_20_pages_free)
```

```{r}
glimpse(foia)
```

# Check NAs

```{r}
foia %>% 
  summarize(across(everything(), ~sum(is.na(.)))) %>% t()
```

```{r}
foia <-
  foia %>% 
  select(-documents)
```

# Check uniques

```{r}
foia %>% 
  summarize(across(everything(), ~length(unique(.)))) %>% t()
```

# assigned_to

```{r}
foia %>% 
  count(assigned_to)
```

```{r}
foia %>% 
  mutate(assigned_to = case_when(
    assigned_to == "Bert" ~ "Bert",
    assigned_to == "Bert." ~ "Bert",
    assigned_to == "Bert`" ~ "Bert",
    TRUE ~ assigned_to
  )) %>% 
  count(assigned_to)
```

# Strings

```{r}
"this is a string"
'so this is also a string'

hello <- "Hello! I am a string too and you can put 'single quotes' in me"
goodbye <- 'This quote has "double" quotes'
```

```{r}
double_in_double <- "Double quotes in \"double\" quotes"
```

```{r}
writeLines(double_in_double)
```

```{r}
spock <- "\\/"
writeLines(spock)
```

```{r}
bus <- c("the", "wheels", "on the bus", "go", "round", "and", "round")
```

`stringr`


```{r}
str_length(bus)
```

```{r}
str_c("clap", "your", "hands", sep = " ")
str_c(bus, collapse = " ")
```

```{r}
substr(bus, 1, 3) # base R
str_sub(bus, 1, 3) # stringr
```

```{r}
str_to_upper(bus)
str_to_title(bus)
str_to_lower(bus)
```

# Regex

```{r}
example_1 <- c("abcdefg", "abcde", "abc")
str_detect(string = example_1, 
           pattern = "abc")
```

# Bert

```{r}
str_detect
str_remove_all
```


```{r}
foia_clean <- 
  foia %>% 
  mutate(assigned_to = str_remove_all(string = assigned_to,
                                      pattern = "[^A-Za-z]"),
         assigned_to = if_else(is.na(assigned_to), "Unassigned", assigned_to))
```

```{r}
foia_clean <-
  foia_clean %>% 
  mutate(internally_reviewed_by = str_remove_all(string = internally_reviewed_by,
                                                 pattern = "[^A-Za-z]"),
         internally_reviewed_by = if_else(is.na(internally_reviewed_by), "Unassigned", internally_reviewed_by))
```

# division

```{r}
foia_clean <- 
  foia_clean %>% 
  mutate(division = case_when(
    str_detect(division, pattern = "Dir") ~ "Director's Office",
    str_detect(division, pattern = "Benefits") ~ "Benefits Office",
    str_detect(division, pattern = "Pension") ~ "Pensions",
    str_detect(division, pattern = "PHRST") ~ "PHRST",
    str_detect(division, pattern = "HR") ~ "HRM",
    str_detect(division, pattern = "OSP") ~ "OSP",
    TRUE ~ division
  ))
```

```{r}
str_detect
```

# is_noncustodial_record

```{r}
foia_clean <- 
  foia_clean %>% 
  mutate(is_noncustodial_record = case_when(
    str_detect(is_noncustodial_record, pattern = "[Nn][Oo]") ~ "No",
    str_detect(is_noncustodial_record, pattern = "[Yy][Ee][Ss]") ~ "Yes",
    TRUE ~ is_noncustodial_record
  ))
```

# all_requested_records_sent

## all_requested_records_sent_flag

```{r}
foia_clean <- 
  foia_clean %>% 
  mutate(all_requested_records_sent_flag = case_when(
    str_detect(all_requested_records_sent, pattern = "^[Yy]") ~ "Yes",
    str_detect(all_requested_records_sent, pattern = "^[Nn]") ~ "No",
    str_detect(all_requested_records_sent, pattern = "^[^YyNnPp]") ~ "Other",
    TRUE ~ all_requested_records_sent
  ))
```

## all_requested_records_sent_detail

```{r}
foia_clean <- 
  foia_clean %>% 
  mutate(all_requested_records_sent_detail = str_remove_all(string = all_requested_records_sent,
                                                            pattern = "^[YyNnPp][A-Za-z,]+[\\s]*"))
```

```{r}
foia_clean %>% 
  count(all_requested_records_sent, all_requested_records_sent_flag, all_requested_records_sent_detail)
```

# Who was assigned the most requests?

```{r}
foia_clean %>% 
  count(assigned_to) %>% 
  ggplot(aes(x = n,
             y = assigned_to)) +
  geom_col()
```

# Factors

```{r}
likert <- c(
  "Strongly Agree",
  "Agree",
  "Neutral",
  "Disagree",
  "Strongly Disagree"
)
```

```{r}
sort(likert)
```

```{r}
likert_leveled <- factor(likert, levels = likert)
```

```{r}
sort(likert_leveled)
```

```{r}
set.seed(1231)

sample_survey <-
  data.frame(ID = 1:1000,
             q1 = sample(likert, size = 1000, replace = T),
             q2 = sample(likert, size = 1000, replace = T),
             q3 = round(runif(1000, 1, 5)),
             stringsAsFactors = F)
```

```{r}
sample_survey %>% 
  mutate(q1 = factor(q1, levels = likert)) %>% 
  ggplot(aes(y = q1)) +
  geom_bar()
```

# forcats

```{r}
assigned_order <- c("Unassigned", "Jessica", "Bert")

foia_clean %>% 
  count(assigned_to) %>% 
  mutate(assigned_to = factor(assigned_to, levels = assigned_order)) %>% 
  ggplot(aes(x = n,
             y = assigned_to)) +
  geom_col()
```

```{r}
foia_clean %>% 
  count(assigned_to) %>% 
  mutate(assigned_to = factor(assigned_to, levels = assigned_order),
         assigned_to = fct_rev(assigned_to)) %>% 
  ggplot(aes(x = n,
             y = assigned_to)) +
  geom_col()
```

# division

```{r}
foia_clean %>% 
  count(division) %>% 
  mutate(division = fct_reorder(division, n)) %>% 
  filter(! is.na(division)) %>% 
  ggplot(aes(x = n,
             y = division)) +
  geom_col() +
  labs(title = "Divisions that receive the most FOIA requests at OMB",
       x = "",
       y = "")
```

# requesting_party

```{r}
foia_clean %>% 
  mutate(requesting_party = fct_lump(requesting_party, n = 10)) %>% 
  count(requesting_party, sort = T) %>% 
  mutate(requesting_party = fct_reorder(requesting_party, n)) %>% 
  ggplot(aes(x = n,
             y = requesting_party)) +
  geom_col()
  
```

# Dates

```{r}
"2021-11-01"
"21/11/1"
"1/11/21"
"11/1/2021"
"November 1, 2021"
```

```{r}
as.Date("2021-11-01")
as.Date("21/11/1")
as.Date("1/11/21")
as.Date("11/1/2021")
as.Date("November 1, 2021")
```

```{r}
as.Date("2021-11-01", format = "%Y-%m-%d")
```

```{r}
as.Date("21/11/1")
as.Date("21/11/1", format = "%y/%m/%d")
```

```{r}
as.Date("1/11/21")
as.Date("1/11/21", format = "%d/%m/%y")
```

```{r}
as.Date("11/1/2021")
as.Date("11/1/2021", format = "%m/%d/%Y")
```

```{r}
# as.Date("November 1, 2021")
as.Date("November 1, 2021", format = "%B %d, %Y")
```

# lubridate

```{r}
ymd("2021-11-01")
ymd("21/11/1")
dmy("1/11/21")
mdy("11/1/2021")
mdy("November 1, 2021")
```

```{r}
ymd_hm("2021-11-01 21:12")
```

```{r}
glimpse(foia_clean)
```

```{r}
foia_clean %>% 
  mutate(received_diff = date_assigned - date_received,
         .keep = "used")
```

